# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGsiRtcXz6oRn_XUw0BiKUBaPFyYONDg
"""

import numpy as np
import matplotlib.pyplot as plt

t=np.linspace(0,1000,210)

k=((1e-4)-900)*np.sin(30*t)*np.exp(t/100)+(6/10)*np.cos(30*t)*np.exp(t/100)
plt.plot(t,k)
plt.xlabel('Time')
plt.ylabel(r'$F_{rad}$')
plt.title('Retardation force vs time plot')
plt.show()