# -*- coding: utf-8 -*-
"""ED_2_QS_1_NEW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VVlL49Eh0Fyl16Ltc8wnBnx06MfPujVa
"""

import numpy as np
import matplotlib.pyplot as plt
t=1
c=1.0
beta=0.999
q=1.0
gamma=1.0/np.sqrt(1.0-beta**2)

#For the second part of the problem,plotting the field lines
nx=20
ny=20
nz=20
x=np.linspace(-40,40,nx)
y=np.linspace(-40,40,ny)
z=np.linspace(-40,40,nz)
X1,Y1=np.meshgrid(x,y)
X2,Z1=np.meshgrid(x,z)
Y2,Z2=np.meshgrid(y,z)


rprime2=np.sqrt((gamma*(X1-beta*c*t))**2 +Y1**2)+1e-5
Ex1=q*gamma*(X1-beta*c*t)/(rprime2**3)
Ey1=q*gamma*Y1/(rprime2**3)
Ez1=np.zeros_like(Ex1)
Bx1=np.zeros_like(Ex1)
By1=np.zeros_like(Ex1)
Bz1=q*gamma*beta*Y1/(rprime2**3)


rprime3=np.sqrt((gamma*(X2-beta*c*t))**2 +Z1**2)+1e-5
Ex2=q*gamma*(X2-beta*c*t)/(rprime3**3)
Ey2=np.zeros_like(Ex2)
Ez2=q*gamma*Z1/(rprime3**3)
Bx2=np.zeros_like(Ex2)
By2=-q*gamma*beta*Z1/(rprime3**3)
Bz2=np.zeros_like(Ex2)

rprime4=np.sqrt((gamma*(0-beta*c*t))**2 +Y2**2+Z2**2)+1e-5
Ex3=q*gamma*(0-beta*c*t)/(rprime4**3)
Ey3=q*gamma*Y2/(rprime4**3)
Ez3=q*gamma*Z2/(rprime4**3)
Bx3=np.zeros_like(Ex3)
By3=-q*gamma*beta*Z2/(rprime4**3)
Bz3=q*gamma*beta*Y2/(rprime4**3)



E_mag1=np.hypot(Ex1,Ey1)
Exn1,Eyn1=Ex1/E_mag1,Ey1/E_mag1

E_mag2=np.hypot(Ex2,Ez2)
Exn2,Ezn2=Ex2/E_mag2,Ez2/E_mag2

E_mag3=np.hypot(Ey3,Ez3)
Eyn3,Ezn3=Ey3/E_mag3,Ez3/E_mag3

B_mag1=np.hypot(Bx1,By1)
B_mag1[B_mag1==0]=1.0
Bxn1,Byn1=Bx1/B_mag1,By1/B_mag1

B_mag2=np.hypot(Bx2,Bz2)
B_mag2[B_mag2==0]=1.0
Bxn2,Bzn2=Bx2/B_mag2,Bz2/B_mag2

B_mag3=np.hypot(By3,Bz3)
Byn3,Bzn3=By3/B_mag3,Bz3/B_mag3




fig,ax=plt.subplots(2,3,figsize=(10,10))
ax[0,0].quiver(X1,Y1,Exn1,Eyn1,E_mag1,cmap='plasma',scale=25)
ax[0,0].set_title("E(x, y) at z=0")
ax[0,0].set_xlabel("x")
ax[0,0].set_ylabel("y")
ax[0,0].set_aspect('equal')

ax[0,1].quiver(X2,Z1,Exn2,Ezn2,E_mag2,cmap='plasma',scale=25)
ax[0,1].set_title("E(x, z) at y=0")
ax[0,1].set_xlabel("x")
ax[0,1].set_ylabel("z")
ax[0,1].set_aspect('equal')

ax[0,2].quiver(Y2,Z2,Eyn3,Ezn3,E_mag3,cmap='plasma',scale=25)
ax[0,2].set_title("E(y, z) at x=0")
ax[0,2].set_xlabel("y")
ax[0,2].set_ylabel("z")
ax[0,2].set_aspect('equal')


ax[1,0].quiver(X1,Y1,Bxn1,Byn1,B_mag1,cmap='plasma',scale=25)
ax[1,0].set_title("B(x,y) at z=0")
ax[1,0].set_xlabel("x")
ax[1,0].set_ylabel("y")
ax[1,0].set_aspect('equal')

ax[1,1].quiver(X2,Z1,Bxn2,Bzn2,B_mag2,cmap='plasma',scale=25)
ax[1,1].set_title("B(x,z) at y=0")
ax[1,1].set_xlabel("x")
ax[1,1].set_ylabel("z")
ax[1,1].set_aspect('equal')

ax[1,2].quiver(Y2,Z2,Byn3,Bzn3,B_mag3,cmap='plasma',scale=25)
ax[1,2].set_title("B(y,z) at x=0")
ax[1,2].set_xlabel("y")
ax[1,2].set_ylabel("z")
ax[1,2].set_aspect('equal')
plt.tight_layout()
plt.show()

#for 3d plotting
Xd,Yd,Zd=np.meshgrid(np.linspace(-40,40,10),np.linspace(-40,40,10),np.linspace(-40,40,10))

rprimed=np.sqrt((gamma*(Xd-beta*c*t))**2+Yd**2+Zd**2)

Exd=q*gamma*(Xd-beta*c*t)/(rprimed**3)
Eyd=q*gamma*Yd/(rprimed**3)
Ezd=q*gamma*Zd/(rprimed**3)

Bxd=np.zeros_like(Exd)
Byd=-q*gamma*beta*Zd/(rprimed**3)
Bzd=q*gamma*beta*Yd/(rprimed**3)

ax=plt.figure().add_subplot(projection='3d')
ax.quiver(Xd,Yd,Zd,Exd,Eyd,Ezd,length=3,normalize=True)
ax.set_title("Electric field",fontsize=14)
ax.set_xlabel("x"); ax.set_ylabel("y");ax.set_zlabel("z")
plt.show()
ax=plt.figure().add_subplot(projection='3d')
ax.quiver(Xd,Yd,Zd,Bxd,Byd,Bzd,length=3,normalize=True)
ax.set_title("Magnetic field",fontsize=14)
ax.set_xlabel("x"); ax.set_ylabel("y");ax.set_zlabel("z")
plt.show()