# -*- coding: utf-8 -*-
"""ED_2_QS_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rg2Fw6teQ9j6Avqd9_5FgwnmsBGegKi1
"""

import numpy as np
import matplotlib.pyplot as plt
h=6.626e-34
k=1.38e-23

p=h/k
NU1=np.logspace(-3,20,500)
l1=lambda T,NU: T**(-0.5)*(2.2+2.2*(p*NU/T)+0.6*(p*NU/T)**2)*np.exp(-p*NU/T)
plt.plot(NU1,l1(300,NU1),label='300K')
plt.plot(NU1,l1(1e6,NU1),label=r'$10^6K$')
plt.title('Thermal Bremsstraluang at two different temperatures')
plt.xlabel('Frequency')
plt.ylabel(r'$\propto\frac{dw}{dvd\nu\omega}$')
plt.semilogx()
plt.legend()
plt.show()